#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se () {
	paths=(~/.local/bin )  # Add your preferred paths here
	choice="$(find "${paths[@]}" -mindepth 1 -type f | fzf --layout=reverse -i)"
	[ -f "$choice" ] && $EDITOR "$choice"
}

wedit() {
	filepath="$(which $1)"
	[[ -f $filepath ]] && $EDITOR $filepath;
}

cpcat() {
	filepath="$(realpath $1)"
	[[ -f $filepath ]] && cat $filepath | xclip;
	notify-send "$1 copied to clipboard"
}


# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"\
	fzf='fzf --layout=reverse'\
	ytmp3='yt-dlp -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -P $HOME/Music/downloaded'\
	cdd='cd $(find ~/ -type d \( -name ".?*" -prune -o -print \) | fzf +m --height 60% --preview "tree -C -L 1 dirname {}")'

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \
	cheat='cheat -ca' \
	pcheat='cheat -p personal'\
	scheat='\cheat -c -s '
# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	gl='git log --graph --pretty=format:"%C(auto)%h%C(reset) %ad %C(auto)%d%C(reset) %s" --date=format:"%H:%M:%S %b %d, %Y"'\
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \
	x="exit"\
	c="clear"\
	b="buku --suggest"\
	resetcaps='setxkbmap -option' \
	caps='setxkbmap -option caps:swapescape'\
	vpn='netExtender -u rahul.gopalakrishnan -p Iucaa@123 -d LocalDomain moon.iucaa.in:4433'



alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \

alias \
	tnote="cd ~/git/personal/dailynotes/ && $EDITOR $(date -I).md" 
	
