#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi
#swap caps and esc
setxkbmap -option caps:swapescape


# increase key speed via a rate change
xset r rate 300 50

# Roating the monitor for
# xrandr --output DP-1 --primary --pos 0x635 --output DP-2 --pos 1920x0 --rotate left

# Activate dbus variables
#dbus-update-activation-environment --all
exec awesome
#dbus-launch ssh-agent dwm
